name: Siempre el mejor
attire:
  active: null
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  disabled:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - Direccion
    - Numero
    - RepeticionSimple
    - puedeMover
    - hayBolitas
    - OperadorNumerico
    - siguiente
    - previo
    - opuesto
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - Procedimientos primitivos
    - Mis procedimientos
    - AlternativaCompleta
    - Color
    - Direccion
    - Numero
    - puedeMover
    - hayBolitas
    - nroBolitas
    - FuncionesPrimitivas
    - OperadorNumerico
    - OperadorDeComparacion
    - siguiente
    - previo
    - opuesto
    - procedures_defnoreturnnoparams
    - Definicion de procedimientos simples
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.75  