name: El final del pasillo
rules:
  - image: Fondo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: Robot.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
  - image: Pared.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
