name: No encuentro bolitas de color Sur
attire:
  active: null
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  disabled:
    - Mover
    - Sacar
    - IrAlBorde
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - Color
    - Numero
    - procedures_defnoreturnnoparams
    - Procedimientos simples
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - Color
    - Direccion
    - Numero
    - procedures_defnoreturnnoparams
    - Definicion de procedimientos simples
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.75  