name: Super mimo multiplica
attire:
  active: null
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  disabled:
    - Mover
    - Sacar
    - IrAlBorde
    - Direccion
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - Color
    - Direccion
    - Numero
    - nroBolitas
    - OperadorNumerico
    - procedures_defnoreturnnoparams
    - Definicion de procedimientos simples
board:
  active: 3
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.75  