name: Radar
rules:
  - image: RadarAntes.png
    when:
      black: 0
      blue: 0
      green: 0
      head: true
      red: 0
  - image: RadarN.png
    when:
      black: 1
      blue: 0
      green: 0
      head: true
      red: 0
  - image: RadarNE.png
    when:
      black: 1
      blue: 0
      green: 1
      head: true
      red: 0
  - image: RadarNES.png
    when:
      black: 1
      blue: 0
      green: 1
      head: true
      red: 1
  - image: RadarNESO.png
    when:
      black: 1
      blue: 1
      green: 1
      head: true
      red: 1
  - image: RadarNEO.png
    when:
      black: 1
      blue: 1
      green: 1
      head: true
      red: 0
  - image: RadarNS.png
    when:
      black: 1
      blue: 0
      green: 0
      head: true
      red: 1
  - image: RadarNSO.png
    when:
      black: 1
      blue: 1
      green: 0
      head: true
      red: 1
  - image: RadarNO.png
    when:
      black: 1
      blue: 1
      green: 0
      head: true
      red: 0
  - image: RadarE.png
    when:
      black: 0
      blue: 0
      green: 1
      head: true
      red: 0
  - image: RadarES.png
    when:
      black: 0
      blue: 0
      green: 1
      head: true
      red: 1
  - image: RadarESO.png
    when:
      black: 0
      blue: 1
      green: 1
      head: true
      red: 1
  - image: RadarEO.png
    when:
      black: 0
      blue: 1
      green: 1
      head: true
      red: 0
  - image: RadarS.png
    when:
      black: 0
      blue: 0
      green: 0
      head: true
      red: 1
  - image: RadarSO.png
    when:
      black: 0
      blue: 1
      green: 0
      head: true
      red: 1
  - image: RadarO.png
    when:
      black: 0
      blue: 1
      green: 0
      head: true
      red: 0
  - image: Avion1.png
    when:
      black: 0
      blue: 0
      green: 0
      head: false
      red: 1
  - image: Avion2.png
    when:
      black: 0
      blue: 0
      green: 0
      head: false
      red: 2
  - image: Avion3.png
    when:
      black: 0
      blue: 0
      green: 0
      head: false
      red: 3
  - image: Avion4.png
    when:
      black: 0
      blue: 0
      green: 0
      head: false
      red: +
  - image: Fondo.png
    when:
      black: 0
      blue: 0
      green: 0
      head: false
      red: 0
