name: Soporte Técnico
rules:
  - { image: Fondo.png        , when: { black: 0, blue: 0, green: 0, red: 0 } }
  - { image: HallPiso.png     , when: { black: '*', blue: 0, green: 0, red: 0 } }
  - { image: HallEdificio.png , when: { black: 0, blue: '*', green: 0, red: 0 } }
  - { image: Virus1.png       , when: { black: 0, blue: 0, green: 0, red: 1 } }
  - { image: Virus2.png       , when: { black: 0, blue: 0, green: 0, red: 2 } }
  - { image: Virus3.png       , when: { black: 0, blue: 0, green: 0, red: 3 } }
  - { image: Virus4.png       , when: { black: 0, blue: 0, green: 0, red: 4 } }
  - { image: Virus5.png       , when: { black: 0, blue: 0, green: 0, red: 5 } }
  - { image: Virus6.png       , when: { black: 0, blue: 0, green: 0, red: 6 } }
  - { image: MarcaOk.png      , when: { black: 0, blue: 0, green: 1, red: 0 } }
