name: Escapar de la jaula
attire:
  active: Escapar de la jaula
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - RepeticionSimple
    - Color
    - Direccion
    - Numero
    - nroBolitas
    - OperadorNumerico
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - Color
    - Direccion
    - Numero
    - nroBolitas
    - FuncionesPrimitivas
    - OperadorNumerico
    - procedures_defnoreturnnoparams
    - Definicion de procedimientos simples
board:
  active: 4
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.75  