name: Dominó
attire:
  active: Domino
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  defaultToolbox: |
    <category name="Comandos primitivos">
      <block type="Poner"></block>
      <block type="Sacar"></block>
      <block type="Mover"></block>
      <block type="IrAlBorde"></block>
    </category>
    <category name="Repeticiones">
      <block type="RepeticionSimple"></block>
    </category>
    <category name="Expresiones básicas">
      <block type="math_number"></block>
      <block type="ColorSelector"></block>
      <block type="DireccionSelector"></block>
    </category>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
        <block type="procedures_defnoreturn"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: true
    can_edit_board: true
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
