name: Otro ladrillo en la pared
attire:
  active: Paredes
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos primitivos">
      <block type="Mover"></block>
      <block type="IrAlBorde"></block>
    </category>
    <category name="Repeticiones">
      <block type="RepeticionSimple"></block>
    </category>
    <category name="Expresiones básicas">
      <block type="math_number"></block>
      <block type="DireccionSelector"></block>
    </category>
    <category name="Procedimientos primitivos" gbs_custom="PRIMITIVE_PROCEDURES">
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: true
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
