name: 'Apagar la luz, o prenderla'
rules:
  - image: Fondo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: LuzPrendida.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
  - image: LuzApagada.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
