name: Tomateras y luces
rules:
  - image: ParcelaVacia.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: PlantasSinTomates.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 0
  - image: PlantasConTomates.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 1
  - image: SinLuz.png
    when:
      black: 1
      blue: 1
      green: 0
      red: 0
  - image: LuzPrendida.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
  - image: LuzApagada.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
