attire:
  active: Fútbol de robots
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled:
    - IrAlBorde
    - Procedimientos primitivos
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - Procedimientos primitivos
    - Mis procedimientos
    - Color
    - Direccion
    - procedures_defnoreturnnoparams
    - Definicion de procedimientos simples
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: 'Preparando el fútbol de robots, sin procedimientos'
