name: Hansel y Gretel
rules:
  - image: Fondo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: Carreta.png
    when:
      black: 1
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Carreta.png
    when:
      black: 1
      blue: 0
      green: 0
      head: true
      red: 1
  - image: Carreta.png
    when:
      black: 2
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Carreta.png
    when:
      black: 2
      blue: 0
      green: 0
      head: true
      red: 1
  - image: CasaBrujaConHanselYGretel.png
    when:
      black: 3
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Camino.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
  - image: Camino.png
    when:
      black: 2
      blue: 0
      green: 0
      red: 0
  - image: CaminoConMiguitas.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 1
  - image: CaminoConMiguitas.png
    when:
      black: 2
      blue: 0
      green: 0
      red: 1
  - image: CasaBruja.png
    when:
      black: 3
      blue: 0
      green: 0
      red: 0
