name: Una víbora más inquieta
attire:
  active: null
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  defaultToolbox: |
    <category name="Comandos básicos">
      <block type="Program"></block>
      <block type="Poner"></block>
      <block type="Sacar"></block>
      <block type="Mover"></block>
      <block type="IrAlBorde"></block>
      <block type="VaciarTablero"></block>
      <block type="BOOM"></block>
      <block type="Asignacion"></block>
    </category>
    <category name="Valores">
      <block type="math_number"></block>
      <block type="ColorSelector"></block>
      <block type="DireccionSelector"></block>
      <block type="BoolSelector"></block>
    </category>
    <category name="Operadores">
      <block type="OperadorNumerico"></block>
      <block type="OperadorDeComparacion"></block>
      <block type="OperadorLogico"></block>
      <block type="not"></block>
      <block type="siguiente"></block>
      <block type="previo"></block>
      <block type="opuesto"></block>
    </category>
    <category name="Sensores">
      <block type="hayBolitas"></block>
      <block type="puedeMover"></block>
      <block type="nroBolitas"></block>
    </category>
    <category name="Procedimientos" custom="PROCEDURE_CALLS">
      <block type="procedures_defnoreturnnoparams"></block>
      <block type="procedures_defnoreturn"></block>
    </category>
    <category name="Funciones" custom="FUNCTION_CALLS">
      <block type="procedures_defreturnsimple"></block>
      <block type="procedures_defreturnsimplewithparams"></block>
      <block type="procedures_defreturn"></block>
    </category>
    <category name="Estructuras de control">
      <block type="RepeticionSimple"></block>
      <block type="RepeticionCondicional"></block>
      <block type="AlternativaSimple"></block>
      <block type="AlternativaCompleta"></block>
    </category>
    <category name="Interactividad">
      <block type="InteractiveProgram"></block>
      <block type="InteractiveLetterBinding"></block>
      <block type="InteractiveNumberBinding"></block>
      <block type="InteractiveKeyBinding"></block>
    </category>
    <category name="Auxiliares para el docente">
      <block type="ComandoCompletar"></block>
      <block type="ExpresionCompletar"></block>
      <block type="AsociacionDeTeclaCompletar"></block>
    </category>
    <category name="Biblioteca">
    </category>
  disabled: []
  visible:
    - Poner
    - Mover
    - Color
    - Direccion
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true
library:
  visible: false
